# Generated by Django 5.1.6 on 2025-02-26 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Joblist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_role', models.CharField(max_length=300)),
                ('company_name', models.CharField(max_length=400)),
                ('location', models.CharField(max_length=1000)),
                ('required_skill', models.CharField(max_length=5000)),
                ('qualification', models.CharField(max_length=500)),
            ],
        ),
    ]
